import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {useState} from 'react'

import {Header} from '../components/Header'
import {Footer} from '../components/Footer'
import React from 'react'

export default function Home() {

  const [count, setCount] = useState<number>(0);

  const CountUp = () =>{
    setCount(count+1);
  }
  const CountDown = () =>{
    if(count > 0){
      setCount(count-1);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
        <Header />

        <div className={styles.grid}>
 
         <button onClick={CountUp}>カウントアップ</button>
         <button onClick={CountDown}>カウントダウン</button>
         <div>
            {count}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
